name: RDV
favicon: null
layout_spectrum: 0.7996371409390122
typography_spectrum: 0.8801152419764549
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.5039403671398759
  lightness: 0.6819481009151787
  saturation: 0.33613431453704834
  rhythmicContrast: 0.12196992430835962
purpose: []
